# Hi! this is a minimal config file for pond

author_name = 'Your Name Here (Edit this in config.toml)'
blog_name = 'Blog Name (Edit this in config.toml)'

# supported accent colors thanks to pico :D
# default amber blue cyan fuchsia green grey indigo jade lime orange pink pumpkin purple red sand slate violet yellow zinc
accent_color =  'lime'
